language: python
python:
  - "3.8.5"
cache: pip
install:
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.path --unset
  - poetry config virtualenvs.in-project true
  - poetry install -vv
script:
  - python -m pytest tests/
  - python -m flake8 pyhoo/ tests/
  - python -m mypy pyhoo/ tests/
